# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 UCT Prague.
#
# oarepo-validate is free software; you can redistribute it and/or modify it under
# the terms of the MIT License; see LICENSE file for more details.

notifications:
  email: false

os: linux

dist: focal

language: python

matrix:
  fast_finish: true

cache:
  - pip

python:
  - '3.8'


before_install:
  - travis_retry pip install --upgrade pip setuptools py
  - "travis_retry pip install twine wheel coveralls"
  - pip install poetry
  - curl https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.6.2-amd64.deb -o elasticsearch.deb
  - sudo dpkg -i --force-confnew elasticsearch.deb
  - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
  - sudo service elasticsearch restart

install:
  - "travis_retry poetry install --extras tests"
  - cat poetry.lock

before_script:
  - sleep 10

script:
  - "./run-tests.sh"

after_success:
  - coveralls

# check if release tag is the same as version.py tag
before_deploy:
  - |-
    SRCTAG=$(cat oarepo_taxonomies/version.py | grep '__version__' | sed 's/__version__//' | sed 's/=//g' | sed 's/"//g' | sed "s/'//g" | sed 's/[ \t\n]//g')
    test $SRCTAG == $TRAVIS_TAG
